sudo: required
dist: trusty
language: cpp
compiler: g++

install: export CXX="g++-10"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

notifications:
 email:
  on_success: never
  on_failure: always


before_install:
 - sudo apt-get update -qq 
 - sudo apt-get install premake5

script:
 # log c++ compiler erison
 - g++-10 --version
 # generate make files using premake5
 - premake5 gmake2
 # make project executable with 2 virtual cpus -j2
 - make -j8 


